default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: todo123
  host: localhost

development:
  <<: *default
  database: tdl_db

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default
  database: todo_list_production
  username: todo_list
  password: <%= ENV['TODO_LIST_DATABASE_PASSWORD'] %>
